AWSTemplateFormatVersion: "2010-09-09"
Resources:
    S3Bucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketEncryption: 
                ServerSideEncryptionConfiguration: 
                  - 
                    ServerSideEncryptionByDefault: 
                        SSEAlgorithm: "aws:kms"
                        KMSMasterKeyID: "alias/aws/s3"
                    BucketKeyEnabled: true
            VersioningConfiguration: 
                Status: "Enabled"
            OwnershipControls: 
                Rules: 
                  - 
                    ObjectOwnership: "BucketOwnerEnforced"
            PublicAccessBlockConfiguration: 
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
