AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "cfst-1909-145a9dd5eb85d9d9de97c971fb8405-s3bucket-194tyrt6wic9p"
      Tags:
        - Key: "CloudFormationStackId"
          Value: !Sub "${AWS::StackId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: false
      LifecycleConfiguration:
        Rules:
          - Id: "log-rule"
            Status: "Enabled"
            Prefix: "Logs"
            Transitions:
              - TransitionInDays: 90
                StorageClass: "STANDARD_IA"
          - Id: "image-rule"
            Status: "Enabled"
            Prefix: "Images"
            Transitions:
              - TransitionInDays: 30
                StorageClass: "ONEZONE_IA"
          - Id: "tagged-logs"
            Status: "Enabled"
            TagFilters:
              - Key: "Type"
                Value: "OldLogs"
            Transitions:
              - TransitionInDays: 180
                StorageClass: "DEEP_ARCHIVE"
      VersioningConfiguration:
        Status: "Enabled"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
